     
services:
  db:
    container_name: db-phpunit

    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_phpunit_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ngwordgames
      - MYSQL_DATABASE=ngwordgames
      - MYSQL_USER=ngwordgames
      - MYSQL_PASSWORD=ngwordgames
    ports:
      - 33061:3306
  
 

volumes:
  db_phpunit_data: